---
title: "EDA"
format:
  html:
    theme: cosmo
    toc: true
    output-dir: docs
editor_options: 
  chunk_output_type: console
---
### Introduction 
 briefly describes the data and the variables you have to work with (just discuss the ones you’ll inves
tigate/use in your analysis).
 • describes the purpose of your EDA and ultimate goal of modeling

Necessary libraries
```{r}
library(tidyr)
library(dplyr)
library(readr)
```


import data 
```{r}
diabetes_data <- read_csv("data/diabetes_012_health_indicators_BRFSS2015.csv")
```

cleaning the data
```{r}
#check for missing values
diabetes_data |>
  is.na() |>
  colSums() #not missing any values
```

```{r}
#check column types and values 
attributes(diabetes_data)$spec
```

```{r}
#change incorrect column types
diabetes_data$Diabetes_012 <- factor(diabetes_data$Diabetes_012,
                                     levels = c(0, 1, 2),
                                     labels = c("No diabetes", "Prediabetes", "Diabetes"))

diabetes_data$HighBP <- factor(diabetes_data$HighBP,
                                     levels = c(0, 1),
                                     labels = c("No high BP", "High BP"))

diabetes_data$HighChol <- factor(diabetes_data$HighChol,
                                     levels = c(0, 1),
                                     labels = c("No high cholesterol", "high cholesterol"))

diabetes_data$CholCheck <- factor(diabetes_data$CholCheck,
                                     levels = c(0, 1),
                                     labels = c("No cholesterol check in 5 years", "Cholesterol check in 5 years"))

diabetes_data$Smoker <- factor(diabetes_data$Smoker,
                                     levels = c(0, 1),
                                     labels = c("smoker", "not a smoker")) #a smoker has smoked 5 packs (100 cigarettes in entire life)

diabetes_data$Stroke <- factor(diabetes_data$Stroke,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$HeartDiseaseorAttack <- factor(diabetes_data$HeartDiseaseorAttack,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$PhysActivity <- factor(diabetes_data$PhysActivity,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$Fruits <- factor(diabetes_data$Fruits,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$Veggies <- factor(diabetes_data$Veggies,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$HvyAlcoholConsump <- factor(diabetes_data$HvyAlcoholConsump,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$AnyHealthcare <- factor(diabetes_data$AnyHealthcare,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$NoDocbcCost <- factor(diabetes_data$NoDocbcCost,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$GenHlth <- factor(diabetes_data$GenHlth,
                                     levels = c(1, 2, 3, 4, 5),
                                     labels = c("Excellent", "Very good", "Good", "Fair", "Poor"))

diabetes_data$DiffWalk <- factor(diabetes_data$DiffWalk,
                                     levels = c(0, 1),
                                     labels = c("No", "Yes"))

diabetes_data$Sex <- factor(diabetes_data$Sex,
                                     levels = c(0, 1),
                                     labels = c("Female", "Male"))

diabetes_data$Age <- factor(diabetes_data$Age,
                                     levels = c(1, 2, 3, 4, 5, 6, 7, 8,  9, 10, 11, 12, 13),
                                     labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64","65-69", "70-74", "75-79", "80 or Older"))

diabetes_data$Education <- factor(diabetes_data$Education,
                                     levels = c(1, 2, 3, 4, 5, 6),
                                     labels = c("Never attended or kindergarden", "Completed Elementary", "Completed Middle", "Completed Highschool","Some college", "College 4 or more years" ))

diabetes_data$Income <- factor(diabetes_data$Income,
                                     levels = c(1, 5, 8),
                                     labels = c("<10000", "<35000", ">=75000"))

diabetes_data
```

[Click here for the Modeling Page](Modeling.html)
